apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-scripts
  labels:
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  preprocess.sh: {{- .Values.dataProcess.scriptProcessor.source | toYaml | indent 2}}