# Default values for fluid.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

workdir: /tmp

# Change the helm backend storage driver used by Fluid's controllers. 
# For now, only "configmap" and "secret" are supported.
helmDriver: configmap

# Default registry, namespace and version tag for images managed by fluid
imagePrefix: &defaultImagePrefix fluidcloudnative
version: &defaultVersion v1.0.2-ca7a430

crdUpgrade:
  enabled: true
  # This sets the time-to-live (TTL) for crd-upgrade jobs. Default is 259200 seconds (3 days).
  ttlSecondsAfterFinished: 259200 
  imagePrefix: *defaultImagePrefix
  image: fluid-crd-upgrader
  tag: *defaultVersion

##  if unspecified, will use built-in variable `.Release.Namespace`.
namespace: fluid-system

image:
  imagePullSecrets: []

dataset:
  replicas: 1
  tolerations:
    - operator: Exists
  controller:
    imagePrefix: *defaultImagePrefix
    image: dataset-controller
    tag: *defaultVersion

csi:
  tolerations:
    - operator: Exists
  featureGates: "FuseRecovery=false"
  config:
    hostNetwork: false
  registrar:
    imagePrefix: *defaultImagePrefix
    image: csi-node-driver-registrar
    tag: v2.3.0
  plugins:
    imagePrefix: *defaultImagePrefix
    image: fluid-csi
    tag: *defaultVersion
  kubelet:
    kubeConfigFile: /etc/kubernetes/kubelet.conf
    certDir: /var/lib/kubelet/pki
    rootDir: /var/lib/kubelet
  pruneFs: fuse.alluxio-fuse,fuse.jindofs-fuse,fuse.juicefs,fuse.goosefs-fuse,ossfs,alifuse.aliyun-alinas-efc
  recoverWarningThreshold: 50
  # default method is "bindMount", "symlink" is also support
  # Notice: if use nodePublishMethod symlink, fuse recovery is not support
  nodePublishMethod: bindMount
  hostPID: false

runtime:
  criticalFusePod: true
  syncRetryDuration: 15s
  mountRoot: /runtime-mnt
  alluxio:
    replicas: 1
    tolerations:
      - operator: Exists
    runtimeWorkers: 3
    portRange: 20000-26000
    portAllocatePolicy: random
    enabled: false
    init:
      imagePrefix: *defaultImagePrefix
      image: init-users
      tag: v0.9.0
    controller:
      imagePrefix: *defaultImagePrefix
      image: alluxioruntime-controller
      tag: *defaultVersion
    runtime:
      imagePrefix: alluxio
      image: alluxio-dev
      tag: 2.9.0
    fuse:
      imagePrefix: alluxio
      image: alluxio-dev
      tag: 2.9.0
    mountConfigStorage: configmap
  jindo:
    replicas: 1
    tolerations:
      - operator: Exists
    runtimeWorkers: 3
    portRange: 18000-19999
    portAllocatePolicy: random
    enabled: false
    engine: jindocache
    queryUfsTotal: true
    smartdata:
      imagePrefix: registry.cn-shanghai.aliyuncs.com/jindofs
      image: smartdata
      tag: 6.2.0
    fuse:
      imagePrefix: registry.cn-shanghai.aliyuncs.com/jindofs
      image: jindo-fuse
      tag: 6.2.0
    controller:
      imagePrefix: *defaultImagePrefix
      image: jindoruntime-controller
      tag: *defaultVersion
    init:
      portCheck:
        enabled: false
      imagePrefix: *defaultImagePrefix
      image: init-users
      tag: v0.9.0
  goosefs:
    replicas: 1
    tolerations:
      - operator: Exists
    runtimeWorkers: 3
    portRange: 26000-32000
    portAllocatePolicy: random
    enabled: false
    init:
      imagePrefix: *defaultImagePrefix
      image: init-users
      tag: v0.9.0
    controller:
      imagePrefix: *defaultImagePrefix
      image: goosefsruntime-controller
      tag: *defaultVersion
    runtime:
      imagePrefix: ccr.ccs.tencentyun.com/qcloud
      image: goosefs
      tag: v1.2.0
    fuse:
      imagePrefix: ccr.ccs.tencentyun.com/qcloud
      image: goosefs-fuse
      tag: v1.2.0
  juicefs:
    replicas: 1
    tolerations:
      - operator: Exists
    enabled: false
    runtimeWorkers: 3
    controller:
      imagePrefix: *defaultImagePrefix
      image: juicefsruntime-controller
      tag: *defaultVersion
    fuse:
      ceimagePrefix: juicedata
      ceimage: juicefs-fuse
      cetag: ce-v1.1.0-rc1
      eeimagePrefix: juicedata
      eeimage: juicefs-fuse
      eetag: ee-4.9.16
  thin:
    replicas: 1
    tolerations:
      - operator: Exists
    enabled: false
    controller:
      imagePrefix: *defaultImagePrefix
      image: thinruntime-controller
      tag: *defaultVersion
    fuse:
      configStorage: configmap
  efc:
    replicas: 1
    tolerations:
      - operator: Exists
    enabled: false
    controller:
      imagePrefix: *defaultImagePrefix
      image: efcruntime-controller
      tag: *defaultVersion
      imagePullPolicy: Always
    init:
      imagePrefix: registry.cn-zhangjiakou.aliyuncs.com/nascache
      image: init-alifuse
      tag: v1.2.2-19dcee9
    master:
      imagePrefix: registry.cn-zhangjiakou.aliyuncs.com/nascache
      image: efc-master
      tag: v1.2.2-19dcee9
    worker:
      imagePrefix: registry.cn-zhangjiakou.aliyuncs.com/nascache
      image: efc-worker
      tag: v1.2.2-19dcee9
    fuse:
      imagePrefix: registry.cn-zhangjiakou.aliyuncs.com/nascache
      image: efc-fuse
      tag: v1.2.2-19dcee9
  vineyard:
    replicas: 1
    portRange: 32000-34000
    tolerations:
      - operator: Exists
    enabled: false
    controller:
      imagePrefix: *defaultImagePrefix
      image: vineyardruntime-controller
      tag: *defaultVersion
      imagePullPolicy: Always
    master:
      imagePrefix: registry.aliyuncs.com/vineyard
      image: vineyardd
      tag: v0.22.2
    worker:
      imagePrefix: registry.aliyuncs.com/vineyard
      image: vineyardd
      tag: v0.22.2
    fuse:
      imagePrefix: registry.aliyuncs.com/vineyard
      image: vineyard-fluid-fuse
      tag: v0.22.2

webhook:
  enabled: true
  imagePrefix: *defaultImagePrefix
  image: fluid-webhook
  tag: *defaultVersion
  replicas: 1
  timeoutSeconds: 15
  reinvocationPolicy: IfNeeded
  tolerations:
    - operator: Exists
  # if configmap `webhook-plugins` exists and not want to replace the content, set this to false.
  forceReplacePluginsProfile: false
  pluginsProfile:
    plugins:
      # serverful webhook plugins
      serverful:
        withDataset:
          - RequireNodeWithFuse
          - NodeAffinityWithCache
          - MountPropagationInjector
        withoutDataset:
          - PreferNodesWithoutCache
      # serverless webhook plugins
      serverless:
        withDataset:
          - FuseSidecar
        withoutDataset: []
    pluginConfig:
      - name: NodeAffinityWithCache
        # plugin args is a serialized yaml string.
        args: |
          preferred:
            # fluid.io/fuse is a fluid built-in affinity, prefer to schedule pods to nodes with runtime fuse pods.
            # - name: fluid.io/fuse
            #   weight: 100
            # fluid.io/node is a fluid built-in affinity, prefer to schedule pods to nodes with runtime worker pods.
            - name: fluid.io/node
              weight: 100
            # runtime worker's zone label name, can be changed according to k8s environment.
            - name: topology.kubernetes.io/zone
              weight: 50
            # runtime worker's region label name, can be changed according to k8s environment.
            - name: topology.kubernetes.io/region
              weight: 20
          # used when app pod with label fluid.io/dataset.{dataset name}.sched set true
          required:
            - fluid.io/node


fluidapp:
  enabled: true
  replicas: 1
  tolerations:
    - operator: Exists
  controller:
    imagePrefix: *defaultImagePrefix
    image: application-controller
    tag: *defaultVersion
  featureGates: "DataflowAffinity=false"
