apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
data:
  upgrade-crds.sh: |
    #!/bin/bash
    set -e

    for crdfile in $(find charts/fluid/fluid/crds/*.yaml);
    do
      crdshort=${crdfile#*_}
      if [[ $(kubectl get --ignore-not-found -f $crdfile | wc -l) -gt 0 ]]; then
        echo "$crdshort founded, replacing its crd..."
        kubectl replace -f $crdfile
      else
        echo "$crdshort not founded, applying its crd..."
        kubectl apply -f $crdfile
      fi
    done
---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: {{ .Release.Namespace }}
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      serviceAccountName: fluid-crds-upgrade
      containers:
        - name: fluid-crds-upgrade
          image: {{ .Values.crdUpgrade.image }}
          volumeMounts:
            - name: crd-upgrade
              mountPath: /etc/scripts
              readOnly: true
          command: ["bash", "/etc/scripts/upgrade-crds.sh"]
      volumes:
        - name: crd-upgrade
          configMap:
            name: fluid-crds-upgrade
      restartPolicy: OnFailure
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["create", "get", "list", "watch", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluid-crds-upgrade
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluid-crds-upgrade
subjects:
  - kind: ServiceAccount
    name: fluid-crds-upgrade
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluid-crds-upgrade
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
