kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: csi-nodeplugin-fluid
  namespace: fluid-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: csi-nodeplugin-fluid
  template:
    metadata:
      labels:
        app: csi-nodeplugin-fluid
    spec:
      serviceAccount: fluid-csi-admin
      tolerations:
      - operator: Exists
      #priorityClassName: system-node-critical
#      hostNetwork: true
#      hostPID: true
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: type
                operator: NotIn
                values:
                - virtual-kubelet
      containers:
        - name: external-attacher
          image: "{{ .Values.csi.attacher.image }}"
          args:
            - --v=5
            - --csi-address={{ .Values.csi.kubelet.rootDir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
#            - --leader-election
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.csi.kubelet.rootDir }}
        - name: node-driver-registrar
          image: "{{ .Values.csi.registrar.image }}"
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "rm -rf /registration/fluid /registration/fuse.csi.fluid.io-reg.sock"]
          args:
            - --v=5
            - --csi-address={{ .Values.csi.kubelet.rootDir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
            - --kubelet-registration-path={{ .Values.csi.kubelet.rootDir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
          env:
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          ports:
            - containerPort: 8080
              name: metrics
              protocol: TCP
          volumeMounts:
            - name: kubelet-dir
              mountPath: {{ .Values.csi.kubelet.rootDir }}
            - name: registration-dir
              mountPath: /registration
        - name: plugins
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add: ["SYS_ADMIN"]
            allowPrivilegeEscalation: true
          image: "{{ .Values.csi.plugins.image }}"
          command: ["/usr/local/bin/entrypoint.sh"]
          args :
            - "--nodeid=$(NODE_ID)"
            - "--endpoint=$(CSI_ENDPOINT)"
            - --v=5
          env:
            - name: NODE_ID
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBELET_ROOTDIR
              value: {{ .Values.csi.kubelet.rootDir }}
            - name: CSI_ENDPOINT
              value: unix://{{ .Values.csi.kubelet.rootDir }}/csi-plugins/fuse.csi.fluid.io/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: plugin-dir
              mountPath: /plugin
            - name: kubelet-dir
              mountPath: {{ .Values.csi.kubelet.rootDir }}
              mountPropagation: "Bidirectional"
            - name: fluid-src-dir
              mountPath: {{ .Values.runtime.mountRoot | quote }}
              mountPropagation: "Bidirectional"
            - name: docker-sock
              mountPath: /var/run/docker.sock
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
        - name: kubelet-dir
          hostPath:
            path: {{ .Values.csi.kubelet.rootDir }}
            type: Directory
        - name: plugin-dir
          hostPath:
            path: {{ .Values.csi.kubelet.rootDir }}/plugins/csi-fluid-plugin
            type: DirectoryOrCreate
        - hostPath:
            path: {{ .Values.csi.kubelet.rootDir }}/plugins_registry
            type: DirectoryOrCreate
          name: registration-dir
        - hostPath:
            path: {{ .Values.runtime.mountRoot | quote }}
            type: DirectoryOrCreate
          name: fluid-src-dir
