name: ""

dataprocess:
  targetDataset: ""
  scriptProcessor:
    image: ""
    imagePullPolicy: IfNotPresent
    command: []
    args: []
    envs: []
    volumes: []
    volumeMounts: []
  jobProcessor:
    podTemplate: {}