name: ""

dataProcess:
  targetDataset: ""
  labels: {}
  annotations: {}
  serviceAccountName: ""
  scriptProcessor:
    image: ""
    imagePullPolicy: IfNotPresent
    restartPolicy: Never
    command: []
    args: []
    source: ""
    envs: []
    volumes: []
    volumeMounts: []
  jobProcessor:
    podSpec: {}
