---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluid-csi
  namespace: fluid-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluid-csi-plugin
rules:
  - apiGroups: ["data.fluid.io"]
    resources:
      - alluxioruntimes
      - jindoruntimes
      - goosefsruntimes
      - alluxioruntimes/status
      - jindoruntimes/status
      - goosefsruntimes/status
      - datasets/status
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: fluid-csi-plugin
subjects:
  - kind: ServiceAccount
    name: fluid-csi
    namespace: fluid-system
roleRef:
  kind: ClusterRole
  name: fluid-csi-plugin
  apiGroup: rbac.authorization.k8s.io