name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    
    - uses: actions/checkout@v2
    
    - name: echo GOPATH
      run: |
        echo $(go env GOPATH)
        pwd
        ls
      
    - name: Build
      run: make build
